location_index:
    path:     /
    defaults: { _controller: "VeloBundle:Location:index" }
    methods:  GET

location_show:
    path:     /{id}/show
    defaults: { _controller: "VeloBundle:Location:show" }
    methods:  GET

location_new:
    path:     /new
    defaults: { _controller: "VeloBundle:Location:new" }
    methods:  [GET, POST]

location_edit:
    path:     /{id}/edit
    defaults: { _controller: "VeloBundle:Location:edit" }
    methods:  [GET, POST]

location_delete:
    path:     /{id}/delete
    defaults: { _controller: "VeloBundle:Location:delete" }
    methods:  DELETE
location_calcule_prix:
    path:     /calcule/{idVelo}/{nbHeur}
    defaults: { _controller: "VeloBundle:Location:calcul" }
    methods:  GET